name: GitHub Actions Demo
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event name
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Echo OS
        run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Configure AWS credentials # Dieser Schritt konfiguriert AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          # Füge die folgende Zeile nur hinzu, wenn du einen Session Token benutzt:
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      # Nachfolgende Schritte können AWS CLI-Befehle verwenden
      # Beispiel: Liste der S3 Buckets
      - name: List S3 Buckets
        run: aws s3 ls
